<a href="https://colab.research.google.com/github/leonardonels/Colab-python/blob/main/Esercizio_numpy_in_aula_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**1. Creazione dell'array**

Definisci una funzione che crea un array NumPy di due dimensioni (30 * 24) che riporta le temperature orarie del mese di Settembre.

Inizializza i valori con numeri decimali casuali compresi tra 10 e 30 gradi Celsius (tip: usa *np.random.uniform()*).

Note: for reproducibility, set seed at the beginning of the function definition using *np.random.seed(100)*



In [53]:
def crea():
  np.random.seed(100)
  return np.random.uniform(10,30,(30,24))

In [54]:
temp=crea()

In [55]:
temp

array([[20.86809884, 15.5673877 , 18.49035181, 26.89552265, 10.09437712,
        12.43138242, 23.41498169, 26.5170551 , 12.73413179, 21.50186659,
        27.82643909, 14.18404244, 13.70656439, 12.16753781, 14.39394985,
        29.57247569, 26.23366298, 13.43882025, 26.32449497, 15.48147494,
        18.63408367, 28.80059639, 26.35298758, 16.722239  ],
       [13.50820907, 17.45664093, 10.11377015, 15.04852707, 25.91325017,
        10.30509942, 21.97686754, 22.07609078, 12.10295371, 17.6388689 ,
        10.72952113, 27.80823127, 29.61841714, 11.19883978, 27.81091889,
        21.53802999, 24.84959378, 22.60367873, 21.63684385, 10.40878264,
        14.20053155, 20.89369756, 25.38230342, 15.01390458],
       [15.71791381, 27.04790176, 29.50012987, 27.69706587, 17.19015688,
        21.97717892, 17.09591223, 16.80380431, 13.56161979, 14.75388417,
        10.89724565, 20.10862859, 17.52504909, 21.85610802, 22.59883751,
        12.85200629, 28.67682599, 28.92759762, 22.04593315, 17.75532561,
  

**2. Temperatura più alta e più bassa**

Trova i valori di temperatura più alta e più bassa

In [56]:
np.max(temp)

29.989583022645874

In [57]:
np.min(temp)

10.009735189505198

**3. Temperatura media giornaliera**

Per ogni giorno (quindi per ogni riga), calcola la temperatura media e crea un nuovo array di 30 elementi che rappresenta la temperatura media giornaliera.

Trova i giorni con la temperatura media più alta e la temperatura media più bassa.

In [58]:
temp.mean(1)

array([19.68143853, 18.7430655 , 19.4335754 , 20.04489722, 20.95753723,
       19.1845319 , 20.0116132 , 20.20729821, 21.70057215, 19.24492208,
       21.51829517, 21.02835107, 17.84885348, 18.96841256, 20.43606819,
       20.00310504, 18.74185491, 21.77999959, 19.9265503 , 18.6615174 ,
       19.64396445, 18.71900765, 18.38656266, 18.48062458, 20.88382823,
       22.31720833, 20.9802146 , 21.84572413, 20.56803782, 21.90209697])

In [64]:
np.where(np.max(temp.mean(1))==temp.mean(1))[0][0]

25

In [65]:
np.where(np.min(temp.mean(1))==temp.mean(1))[0][0]

12

**4. Aumento di temperatura**

Sono stati rilevati alcuni problemi nella calibrazione del misuratore, è necessario aumentare di 2 gradi ogni temperatura rispetto a quanto misurato.

In [67]:
temp2=temp+2

In [68]:
temp2

array([[22.86809884, 17.5673877 , 20.49035181, 28.89552265, 12.09437712,
        14.43138242, 25.41498169, 28.5170551 , 14.73413179, 23.50186659,
        29.82643909, 16.18404244, 15.70656439, 14.16753781, 16.39394985,
        31.57247569, 28.23366298, 15.43882025, 28.32449497, 17.48147494,
        20.63408367, 30.80059639, 28.35298758, 18.722239  ],
       [15.50820907, 19.45664093, 12.11377015, 17.04852707, 27.91325017,
        12.30509942, 23.97686754, 24.07609078, 14.10295371, 19.6388689 ,
        12.72952113, 29.80823127, 31.61841714, 13.19883978, 29.81091889,
        23.53802999, 26.84959378, 24.60367873, 23.63684385, 12.40878264,
        16.20053155, 22.89369756, 27.38230342, 17.01390458],
       [17.71791381, 29.04790176, 31.50012987, 29.69706587, 19.19015688,
        23.97717892, 19.09591223, 18.80380431, 15.56161979, 16.75388417,
        12.89724565, 22.10862859, 19.52504909, 23.85610802, 24.59883751,
        14.85200629, 30.67682599, 30.92759762, 24.04593315, 19.75532561,
  

In [72]:
np.max(temp2)

31.989583022645874

**5. Modifica di alcuni valori**

Modifica i valori dell'array in modo che il valore massimo possibile sia 30.

In [95]:
templimit=temp2
templimit[temp2>30]=30
templimit

array([[22.86809884, 17.5673877 , 20.49035181, 28.89552265, 12.09437712,
        14.43138242, 25.41498169, 28.5170551 , 14.73413179, 23.50186659,
        29.82643909, 16.18404244, 15.70656439, 14.16753781, 16.39394985,
        30.        , 28.23366298, 15.43882025, 28.32449497, 17.48147494,
        20.63408367, 30.        , 28.35298758, 18.722239  ],
       [15.50820907, 19.45664093, 12.11377015, 17.04852707, 27.91325017,
        12.30509942, 23.97686754, 24.07609078, 14.10295371, 19.6388689 ,
        12.72952113, 29.80823127, 30.        , 13.19883978, 29.81091889,
        23.53802999, 26.84959378, 24.60367873, 23.63684385, 12.40878264,
        16.20053155, 22.89369756, 27.38230342, 17.01390458],
       [17.71791381, 29.04790176, 30.        , 29.69706587, 19.19015688,
        23.97717892, 19.09591223, 18.80380431, 15.56161979, 16.75388417,
        12.89724565, 22.10862859, 19.52504909, 23.85610802, 24.59883751,
        14.85200629, 30.        , 30.        , 24.04593315, 19.75532561,
  

In [94]:
np.where(temp2>30,30,temp2)

array([[22.86809884, 17.5673877 , 20.49035181, 28.89552265, 12.09437712,
        14.43138242, 25.41498169, 28.5170551 , 14.73413179, 23.50186659,
        29.82643909, 16.18404244, 15.70656439, 14.16753781, 16.39394985,
        30.        , 28.23366298, 15.43882025, 28.32449497, 17.48147494,
        20.63408367, 30.        , 28.35298758, 18.722239  ],
       [15.50820907, 19.45664093, 12.11377015, 17.04852707, 27.91325017,
        12.30509942, 23.97686754, 24.07609078, 14.10295371, 19.6388689 ,
        12.72952113, 29.80823127, 30.        , 13.19883978, 29.81091889,
        23.53802999, 26.84959378, 24.60367873, 23.63684385, 12.40878264,
        16.20053155, 22.89369756, 27.38230342, 17.01390458],
       [17.71791381, 29.04790176, 30.        , 29.69706587, 19.19015688,
        23.97717892, 19.09591223, 18.80380431, 15.56161979, 16.75388417,
        12.89724565, 22.10862859, 19.52504909, 23.85610802, 24.59883751,
        14.85200629, 30.        , 30.        , 24.04593315, 19.75532561,
  

**6. Quante volte sono stati registrati più di 23 gradi?**

In [76]:
mask_23=temp>23
np.sum(mask_23)

247

In [96]:
np.sum(temp>23)

247

**7. Confronto di valori medi**

Calcola la differenza tra la temperatura media dei primi 3 giorni di Settembre e quella degli ultimi 3 giorni.

In [83]:
temp[0]

array([20.86809884, 15.5673877 , 18.49035181, 26.89552265, 10.09437712,
       12.43138242, 23.41498169, 26.5170551 , 12.73413179, 21.50186659,
       27.82643909, 14.18404244, 13.70656439, 12.16753781, 14.39394985,
       29.57247569, 26.23366298, 13.43882025, 26.32449497, 15.48147494,
       18.63408367, 28.80059639, 26.35298758, 16.722239  ])

In [82]:
print(temp[0][:3])
print(np.mean(temp[0][:3]))

array([20.86809884, 15.5673877 , 18.49035181])

In [84]:
temp[29]

array([24.22939852, 15.46308834, 29.89882853, 17.09455828, 11.77250828,
       29.66500754, 19.58485964, 19.64334041, 20.53090832, 28.86148654,
       19.81407703, 10.60260792, 28.70940686, 24.94560002, 24.60822984,
       12.10562309, 25.31205126, 24.15758089, 28.45076287, 20.18142725,
       24.24219937, 27.42096643, 18.6132363 , 19.74257382])

In [92]:
print(temp[29][21:])
print(np.mean(temp[29][12:]))

[27.42096643 18.6132363  19.74257382]
23.207471500209817


In [91]:
np.abs(np.mean(temp[0][:3])-np.mean(temp[29][21:]))

3.6169794002246434

In [118]:
temp.shape

(30, 24)

In [129]:
np.concatenate((temp,np.median(temp, axis=1).reshape(30,1)), axis=1)

array([[20.86809884, 15.5673877 , 18.49035181, 26.89552265, 10.09437712,
        12.43138242, 23.41498169, 26.5170551 , 12.73413179, 21.50186659,
        27.82643909, 14.18404244, 13.70656439, 12.16753781, 14.39394985,
        29.57247569, 26.23366298, 13.43882025, 26.32449497, 15.48147494,
        18.63408367, 28.80059639, 26.35298758, 16.722239  , 18.56221774],
       [13.50820907, 17.45664093, 10.11377015, 15.04852707, 25.91325017,
        10.30509942, 21.97686754, 22.07609078, 12.10295371, 17.6388689 ,
        10.72952113, 27.80823127, 29.61841714, 11.19883978, 27.81091889,
        21.53802999, 24.84959378, 22.60367873, 21.63684385, 10.40878264,
        14.20053155, 20.89369756, 25.38230342, 15.01390458, 19.26628323],
       [15.71791381, 27.04790176, 29.50012987, 27.69706587, 17.19015688,
        21.97717892, 17.09591223, 16.80380431, 13.56161979, 14.75388417,
        10.89724565, 20.10862859, 17.52504909, 21.85610802, 22.59883751,
        12.85200629, 28.67682599, 28.92759762, 22

In [130]:
np.concatenate((temp,np.median(temp, axis=1).reshape(30,1)), axis=1).shape

(30, 25)